---
machines:
  aa_web:
    hostname: "aa_web"
    ipv4: "192.168.72.10"
    playbook: "provisioning/ansible/web_server.yml"
    folder_map:
    - guest: "/opt/www"
      host: "../../byng_systems@bitbucket.org/affinity-authservice-app/"
      owner: www-data
      group: www-data

  aa_db:
    hostname: "aa_db"
    ipv4: "192.168.72.20"
    playbook: "provisioning/ansible/db_server.yml"
